name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev  # Ajouter si vous utilisez une branche de développement

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Assurez-vous que cette version correspond à votre projet

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          python -m unittest discover -s tests

      - name: Test API endpoints
        run: |
            curl -X POST -H "Content-Type: application/json" \
            -d '{"height": 1.75, "weight": 70}' http://127.0.0.1:5000/bmi
        